import java.util.HashMap;

import javax.sound.sampled.Control;

public class CountryData {
    public HashMap<String, Country> dataList;

    public void populate() {
        this.dataList.put("Afghanistan", new Country("Kabul", 40100000, "Asia", "Persian, Pashto"));
        this.dataList.put("Albania", new Country("Tirana", 2800000, "Europe", "Albanian"));
        this.dataList.put("Algeria", new Country("Algiers", 44200000, "Africa", "Arabic, Tamazight"));
        this.dataList.put("Andorra", new Country("Andorra la Vella", 79000, "Europe", "Catalan"));
        this.dataList.put("Angola", new Country("Luanda", 34500000, "Africa", "Portuguese"));
        this.dataList.put("Antigua and Barbuda", new Country("Saint John's", 93000, "North America", "English"));
        this.dataList.put("Argentina", new Country("Buenos Aires", 45800000, "South America", "no official language"));
        this.dataList.put("Armenia", new Country("Yerevan", 2800000, "Asia", "Armenian"));
        this.dataList.put("Austrailia", new Country("Canberra", 25700000, "Oceania", "no official language"));
        this.dataList.put("Austria", new Country("Vienna", 8900000, "Europe", "German"));
        this.dataList.put("Azerbaijan", new Country("Baku", 10100000, "Asia/Europe", "Azerbaijani"));
        this.dataList.put("Bahamas", new Country("Nassau", 408000, "North America", "English"));
        this.dataList.put("Bahrain", new Country("Manama", 1400000, "Asia", "Arabic"));
        this.dataList.put("Bangladesh", new Country("Dhaka", 169400000, "Asia", "Bengali"));
        this.dataList.put("Barbados", new Country("Bridgetown", 281000, "North America", "English"));
        this.dataList.put("Belarus", new Country("Minsk", 9300000, "Europe", "Belarusian, Russian"));
        this.dataList.put("Belgium", new Country("Brussels", 11600000, "Europe", "Dutch, French, German"));
        this.dataList.put("Belize", new Country("Belmopan", 400000, "North America", "English"));
        this.dataList.put("Benin", new Country("Porto-Novo", 13000000, "Africa", "French"));
        this.dataList.put("Bhutan", new Country("Thimphu", 777000, "Asia", "Dzongkha"));
        this.dataList.put("Bolivia", new Country("La Paz, Sucre", 12100000, "South America", "Spanish, 36 indigenous languages"));
        this.dataList.put("Bosnia and Herzegovina", new Country("Sarajevo", 3300000, "Europe", "no official language"));
        this.dataList.put("Botswana", new Country("Gaborone", 2600000, "Africa", "English"));
        this.dataList.put("Brazil", new Country("Brasilia", 214300000, "South America", "Portuguese"));
        this.dataList.put("Brunei", new Country("Bandar Seri Begawan", 445000, "Asia", "Malay, English"));
        this.dataList.put("Bulgaria", new Country("Sofia", 6880000, "Europe", "Bulgarian"));
        this.dataList.put("Burkina Faso", new Country("Ouagadougou", 22100000, "Africa", "French"));
        this.dataList.put("Burundi", new Country("Gitega", 12550000, "Africa", "French, Kirundi, English"));
        this.dataList.put("Côte d'Ivoire", new Country("Yamoussoukro", 27480000, "Africa", "French"));
        this.dataList.put("Cabo Verde", new Country("Praia", 588000, "Africa", "Poruguese"));
        this.dataList.put("Cambodia", new Country("Phnom Penh", 16590000, "Asia", "Khmer"));
        this.dataList.put("Cameroon", new Country("Yaoundé", 27200000, "Africa", "English, French"));
        this.dataList.put("Canada", new Country("Ottawa", 38250000, "North America", "English, French"));
        this.dataList.put("Central African Republic", new Country("Bangui", 5460000, "Africa", "French, Sango"));
        this.dataList.put("Chad", new Country("N'Djamena", 17180000, "Africa", "Arabic, French"));
        this.dataList.put("Chile", new Country("Santiago", 19490000, "South America", "Chilean Spanish"));
        this.dataList.put("China", new Country("Beijing", 1412000000, "Asia", "Standard Chinese"));
        this.dataList.put("Colombia", new Country("Bogotá", 51520000, "South America", "Spanish"));
        this.dataList.put("Comoros", new Country("Moroni", 822000, "Africa", "Arabic, Comorian, French"));
        this.dataList.put("Democratic Republic of the Congo", new Country("Kinshasa", 95890000, "Africa", "French"));
        this.dataList.put("Republic of the Congo", new Country("Brazzaville", 5840000, "Africa", "French"));
        this.dataList.put("Costa Rica", new Country("San José", 5150000, "North America", "Spanish"));
        this.dataList.put("Croatia", new Country("Zagreb", 3900000, "Europe", "Croatian"));
        this.dataList.put("Cuba", new Country("Havana" , 11260000, "North America", "Spanish"));
        this.dataList.put("Cyprus", new Country("Nicosia", 1240000, "Europe", "Greek, Turkish"));
        this.dataList.put("Czech Republic", new  Country("Prague", 10510000, "Europe", "Czech, Slovak"));
        this.dataList.put("Denmark", new Country("Copenhagen", 5860000, "Europe", "Danish"));
        this.dataList.put("Djibouti", new Country("Djibouti", 1100000, "Africa", "Arabic, French"));
        this.dataList.put("Dominica", new Country("Roseau", 72000, "North America", "English"));
        this.dataList.put("Dominican Republic", new Country("Santo Domingo", 11120000, "North America", "Spanish"));
        this.dataList.put("East Timor", new Country("Dili", 1320000, "Asia", "Portuguese, Tetum"));
        this.dataList.put("Ecuador", new Country("Quito", 17800000, "South America", "Spanish, Quechua"));
        this.dataList.put("Egypt", new Country("Cairo", 109300000, "Africa", "Arabic"));
        this.dataList.put("El Salvador", new Country("San Salvador", 6310000, "North America", "Spanish"));
        this.dataList.put("Equatorial Guinea", new Country("Malabo", 1630000, "Africa", "French, Portuguese, Spanish"));
        this.dataList.put("Eritrea", new Country("Asmara", 3620000, "Africa", "Tigrinya"));
        this.dataList.put("Estonia", new Country("Tallinn", 1330000, "Europe", "Estonian"));
        this.dataList.put("Eswatini", new Country("Mbabane, Lobamba", 1190000, "Africa", "English, Swazi"));
        this.dataList.put("Ethiopia", new Country("Addis Ababa", 120300000, "Africa", "Afar, Amharic, Oromo, etc"));
        this.dataList.put("Fiji", new Country("Suva", 925000, "Oceania", "English, Fijian, Fiji Hindi"));
        this.dataList.put("Finland", new Country("Helsinki", 5540000, "Europe", "Finnish, Swedish"));
        this.dataList.put("France", new Country("Paris", 67750000, "Europe", "French"));
        this.dataList.put("Gabon", new Country("Libreville", 2340000, "Africa", "French"));
        this.dataList.put("Gambia", new Country("Banjul", 2640000, "Africa", "English"));
        this.dataList.put("Georgia", new Country("Tbilisi", 10800000, "Asia/Europe", "Georgian"));
        this.dataList.put("Germany", new Country("Berlin", 83200000, "Europe", "German"));
        this.dataList.put("Ghana", new Country("Accra", 32830000, "Africa", "English"));
        this.dataList.put("Greece", new Country("Athens", 10640000, "Europe", "Greek"));
        this.dataList.put("Grenada", new Country("Saint George's", 125000, "North America", "English"));
        this.dataList.put("Guatemala", new Country("Guatemala City", 17110000, "North America", "Spanish"));
        this.dataList.put("Guinea", new Country("Conakry", 13530000, "Africa", "French"));
        this.dataList.put("Guinea-Bissau", new Country("Bissau", 2060000, "Africa", "Portuguese"));
        this.dataList.put("Guyana", new Country("Georgetown", 805000, "South America", "English"));
        this.dataList.put("Haiti", new Country("Port-au-Prince", 11450000, "North America", "French, Haitian Creole"));
        this.dataList.put("Honduras", new Country("Tegucigalpa", 1, "North America", "Spanish"));
        this.dataList.put("Hungary", new Country("Budapest", 10280000, "North America", "Hungarian"));
        this.dataList.put("Iceland", new Country("Reykjavík", 373000, "Europe", "Icelandic"));
        this.dataList.put("India", new Country("New Delhi", 1408000000, "Asia", "Hindi, English"));
        this.dataList.put("Indonesia", new Country("Jakarta", 273800000, "Asia", "Indonesian"));
        this.dataList.put("Iran", new Country("Tehran", 87920000, "Asia", "Persian"));
        this.dataList.put("Iraq", new Country("Baghdad", 43530000, "Asia", "Arabic, Kurdish"));
        this.dataList.put("Ireland", new Country("Dublin", 5030000, "Europe", "Irish, English"));
        this.dataList.put("Israel", new Country("Jerusalem", 9360000, "Asia", "Hebrew"));
        this.dataList.put("Italy", new Country("Rome", 59110000, "Europe", "Italian"));
        this.dataList.put("Jamaica", new Country("Kingston", 2830000, "North America", "English"));
        this.dataList.put("Japan", new Country("Tokyo", 125700000, "Asia", "no official language"));
        this.dataList.put("Jordan", new Country("Amman", 11150000, "Asia", "Arabic"));
        this.dataList.put("Kazakhstan", new Country("Astana", 19000000, "Asia", "Kazakh, Russian"));
        this.dataList.put("Kenya", new Country("Nairobi", 53010000, "Africa", "English, Swahili"));
        this.dataList.put("Kiribati", new Country("Tarawa", 129000, "Oceania", "English"));
        this.dataList.put("North Korea", new Country("Pyongyang", 25970000, "Asia", "Korean"));
        this.dataList.put("South Korea", new Country("Seoul", 51740000, "Asia", "Korean"));
        this.dataList.put("Kosovo", new Country("Pristina", 1873000, "Europe", "Albanian, Serbian"));
        this.dataList.put("Kuwait", new Country("Kuwait City", 4250000, "Asia", "Standard Arabic"));
        this.dataList.put("Kyrgyzstan", new Country("Bishkek", 6690000, "Asia", "Kyrgz, Russian"));
        this.dataList.put("Laos", new Country("Vientiane", 7425000, "Asia", "Lao"));
        this.dataList.put("Latvia", new Country("Riga", 1884000, "Europe", "Latvian"));
        this.dataList.put("Lebanon", new Country("Beirut", 5593000, "Asia", "Arabic"));
        this.dataList.put("Lesotho", new Country("Maseru", 2281000, "Africa", "Sotho, English"));
        this.dataList.put("Liberia", new Country("Monrovia", 5193000, "Africa", "English"));
        this.dataList.put("Libya", new Country("Tripoli", 6735000, "Africa", "Arabic"));
        this.dataList.put("Liechtenstein", new Country("Vaduz", 39000, "Europe", "German"));
        this.dataList.put("Lithuania", new Country("Vilnius", 2800000, "Europe", "Lithuanian"));
        this.dataList.put("Luxembourg", new Country("Luxembourg", 640000, "Europe", "French, German, Luxembourgish"));
        this.dataList.put("Madagascar", new Country("Antananarivo", 28920000, "Africa", "French, Malagasy"));
        this.dataList.put("Malawi", new Country("Lilongwe", 19890000, "Africa", "English, Chichewa"));
        this.dataList.put("Malaysia", new Country("Kuala Lumpur", 33570000, "Asia", "Malay"));
        this.dataList.put("Maldives", new Country("Malé", 521000, "Asia", "Dhivehi"));
        this.dataList.put("Mali", new Country("Bamako", 21900000, "Africa", "French"));
        this.dataList.put("Malta", new Country("Valletta", 519000, "Europe", "Maltese, English"));
        this.dataList.put("Marshall Islands", new Country("Majuro, Delap-Uliga-Djarrit", 42000, "Oceania", "English"));
        this.dataList.put("Mauritania", new Country("Nouakchott", 4615000, "Africa", "Arabic"));
        this.dataList.put("Mauritius", new Country("Port Louis", 1266000, "Africa", "English, Mauritian Creole"));
        this.dataList.put("Mexico", new Country("Mexico City", 126700000, "North America", "no official language"));
        this.dataList.put("Micronesia", new Country("Palikir", 113000, "Oceania", "English"));
        this.dataList.put("Moldova", new Country("Chișinău", 2615000, "Europe", "Romanian"));
        this.dataList.put("Monaco", new Country("Monaco", 37000, "Europe", "French"));
        this.dataList.put("Mongolia", new Country("Ulaanbaatar", 3350000, "Asia", "Mongolian"));
        this.dataList.put("Montenegro", new Country("Podgorica", 619000, "Europe", "Montenegrin"));
        this.dataList.put("Morocco", new Country("Rabat", 37080000, "Africa", "Amazigh, Arabic"));
        this.dataList.put("Mozambique", new Country("Maputo", 32080000, "Africa", "Portuguese"));
        this.dataList.put("Myanmar", new Country("Naypyidaw", 53800000, "Asia", "Burmese"));
        this.dataList.put("Namibia", new Country("Windhoek", 2530000, "Africa", "English"));
        this.dataList.put("Nauru", new Country("Yaren", 13000, "Oceania", "English, Nauruan"));
        this.dataList.put("Nepal", new Country("Kathmandu", 30000000, "Asia", "Nepali"));
        this.dataList.put("Netherlands", new Country("Amsterdam", 17530000, "Europe", "Dutch"));
        this.dataList.put("New Zealand", new Country("Wellington", 5120000, "Oceania", "English, Māori"));
        this.dataList.put("Nicaragua", new Country("Managua", 6850000, "South America", "Spanish"));
        this.dataList.put("Niger", new Country("Niamey", 25250000, "Africa", "French"));
        this.dataList.put("Nigeria", new Country("Abuja", 213400000, "Africa", "English"));
        this.dataList.put("Niue", new Country("Alofi", 2000, "Oceania", "English, Niuean"));
        this.dataList.put("North Macedonia", new Country("Skopje", 2065000, "Europe", "Macedonian, Albanian"));
        this.dataList.put("Norway", new Country("Oslo", 5410000, "Europe", "Norwegian, Sami languages"));
        this.dataList.put("Oman", new Country("Muscat", 4520000, "Asia", "Arabic"));
        this.dataList.put("Pakistan", new Country("Islamabad", 231400000, "Asia", "Urdu, English"));
        this.dataList.put("Palau", new Country("Ngerulmud", 18000, "Oceania", "English, Palauan"));
        this.dataList.put("Palestine", new Country("Ramallah", 4923000, "Asia", "no official language"));
        this.dataList.put("Panama", new Country("Panama City", 4350000, "South America", "Spanish"));
        this.dataList.put("Papua New Guinea", new Country("Port Moresby", 9950000, "Oceania", "English, Hiri Motu, Tok Pisin"));
        this.dataList.put("Paraguay", new Country("Asunción", 6704000, "South America", "Spanish, Guaraní"));
        this.dataList.put("Peru", new Country("Lima", 33720000, "South America", "Peruvian Spanish, Quechua, Aymara, Asháninka"));
        this.dataList.put("Philippines", new Country("Manila", 113900000, "Asia", "Filipino, English"));
        this.dataList.put("Poland", new Country("Warsaw", 37750000, "Europe", "Polish"));
        this.dataList.put("Portugal", new Country("Lisbon", 10330000, "Europe", "Portuguese"));
        this.dataList.put("Qatar", new Country("Doha", 2690000, "Asia", "Arabic"));
        this.dataList.put("Romania", new Country("Bucharest", 19120000, "Europe", "Romanian"));
        this.dataList.put("Russia", new Country("Moscow", 143400000, "Europe/Asia", "Russian"));
        this.dataList.put("Rwanda", new Country("Kigali", 13460000, "Africa", "English, French, Kinyarwanda, Swahili"));
        this.dataList.put("Saint Kitts and Nevis", new Country("Basseterre", 48000, "North America", "English"));
        this.dataList.put("Saint Lucia", new Country("Castries", 180000, "North America", "English"));
        this.dataList.put("Saint Vincent and the Grenadines", new Country("Kingstown", 104000, "North America", "English"));
        this.dataList.put("Samoa", new Country("Apia", 219000, "Oceania", "English"));
        this.dataList.put("San Marino", new Country("San Marino", 34000, "Europe", "Italian"));
        this.dataList.put("São Tomé and Príncipe", new Country("São Tomé", 223000, "Africa", "Portuguese"));
        this.dataList.put("Saudi Arabia", new Country("Riyadh", 35950000, "Asia", "Arabic"));
        this.dataList.put("Senegal", new Country("Dakar", 16880000, "Africa", "French"));
        this.dataList.put("Serbia", new Country("Belgrade", 6834000, "Europe", "Serbian"));
        this.dataList.put("Seychelles", new Country("Victoria", 99000, "Africa", "English, French, Seychellois Creole"));
        this.dataList.put("Sierra Leone", new Country("Freetown", 8421000, "Africa", "English"));
        this.dataList.put("Singapore", new Country("Singapore", 5454000, "Asia", "English, Malay, Mandarin Chinese, Tamil"));
        this.dataList.put("Slovakia", new Country("Bratislava", 5450000, "Europe", "Slovak"));
        this.dataList.put("Slovenia", new Country("Ljubljana", 2110000, "Europe", "Slovene"));
        this.dataList.put("Solomon Islands", new Country("Honiara", 708000, "Oceania", "English"));
        this.dataList.put("Somalia", new Country("Mogadishu", 17070000, "Africa", "Arabic"));
        this.dataList.put("South Africa", new Country(" Cape Town, Pretoria", 59390000, "Africa", "Afrikaans, English, Southern Ndebele, etc"));
        this.dataList.put("South Sudan", new Country("Juba", 10750000, "Africa", "English"));
        this.dataList.put("Spain", new Country("Madrid", 47420000, "Europe", "Spanish"));
        this.dataList.put("Sri Lanka", new Country("Colombo, Sri Jayawardenepura Kotte", 22160000, "Asia", "Sinhala, Tamil"));
        this.dataList.put("Sudan", new Country("Khartoum", 45660000, "Africa", "Arabic, English"));
        this.dataList.put("Suriname", new Country("Paramaribo", 613000, "South America", "Dutch"));
        this.dataList.put("Sweden", new Country("Stockholm", 10420000, "Europe", "Swedish"));
        this.dataList.put("Switzerland", new Country("Bern", 8700000, "Europe", "French, German, Italian, Romansh"));
        this.dataList.put("Syria", new Country("Damascus", 21320000, "Asia", "Arabic"));
        this.dataList.put("Taiwan", new Country("Taipei City", 23570000, "Asia", "no official language"));
        this.dataList.put("Tajikistan", new Country("Dushanbe", 9750000, "Asia", "Tajik"));
        this.dataList.put("Tanzania", new Country("Dodoma", 63590000, "Africa", "Swahili, English"));
        this.dataList.put("Thailand", new Country("Bangkok", 71600000, "Asia", "Thai"));
        this.dataList.put("Togo", new Country("Lomé", 8645000, "Africa", "French"));
        this.dataList.put("Tonga", new Country("Nuku'alofa", 106000, "Oceania", "English, Tongan"));
        this.dataList.put("Trinidad and Tobago", new Country("Port of Spain", 1526000, "South America", "English"));
        this.dataList.put("Tunisia", new Country("Tunis", 12260000, "Africa", "Arabic"));
        this.dataList.put("Turkey", new Country("Ankara", 84780000, "Europe/Asia", "Turkish"));
        this.dataList.put("Turkmenistan", new Country("Ashgabat", 6342000, "Asia", "Turkmen"));
        this.dataList.put("Tuvalu", new Country("Funafuti", 11000, "Oceania", "Tuvaluan, English"));
        this.dataList.put("Uganda", new Country("Kampala", 45850000, "Africa", "English, Swahili"));
        this.dataList.put("Ukraine", new Country("Kyiv", 43790000, "Europe", "Ukrainian"));
        this.dataList.put("United Arab Emirates", new Country("Abu Dhabi", 9365000, "Asia", "Arabic"));
        this.dataList.put("United Kingdom", new Country("London", 67300000, "Europe", "English"));
        this.dataList.put("United States", new Country("Washington D.C.", 331900000, "North America", "no official language"));
        this.dataList.put("Uruguay", new Country("Montevideo", 3426000, "South America", "no official language"));
        this.dataList.put("Uzbekistan", new Country("Tashkent", 34920000, "Asia", "Uzbek"));
        this.dataList.put("Vanuatu", new Country("Port Vila", 319000, "Oceania", "English, French"));
        this.dataList.put("Vatican City", new Country("Vatican City", 825, "Europe", "Italian, Latin"));
        this.dataList.put("Venezuela", new Country("Caracas", 28200000, "South America", "Spanish"));
        this.dataList.put("Vietnam", new Country("Hanoi", 97470000, "Asia", "Vietnamese"));
        this.dataList.put("Yemen", new Country("Sana'a", 32980000, "Asia", "Arabic"));
        this.dataList.put("Zambia", new Country("Lusaka", 19470000, "Africa", "English"));
        this.dataList.put("Zimbabwe", new Country("Harare", 15990000, "Africa", "Chewa, Chibarwe, English, etc"));
    }

    public CountryData() {
        this.dataList=new HashMap<String, Country>();
        this.populate();
    }

    public HashMap<String, Country> getDataList(){
        return this.dataList;
    }

}
